# Generated by Django 6.0.4 on 2026-04-12 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('supervisor_teacher', models.CharField(max_length=150)),
                ('exam_room', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['sbd'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_sbd', models.CharField(max_length=20)),
                ('violation_text', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('room_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='violations.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Admin Profile',
                'verbose_name_plural': 'Room Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='IncidentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbd_snapshot', models.CharField(max_length=20)),
                ('relation_type', models.CharField(choices=[('reported', 'Reported'), ('mentioned', 'Mentioned')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_links', to='violations.candidate')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='violations.incident')),
            ],
            options={
                'ordering': ['incident', 'sbd_snapshot'],
                'unique_together': {('incident', 'sbd_snapshot')},
            },
        ),
    ]
